### ISSUE TITLE
Error when run project

### ISSUE THREAD

**Issue by vanloc0301** [GCC15/bilibili-captcha#5]
When run project this show error like:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import dataset_manager
  File "/media/io/HocTap/Lapsoft - Deeep Learning/bilibili-captcha/dataset_manager.py", line 14, in <module>
    from captcha_recognizer import CaptchaRecognizer
  File "/media/io/HocTap/Lapsoft - Deeep Learning/bilibili-captcha/captcha_recognizer.py", line 124
    nonlocal seq
               ^
SyntaxError: invalid syntax

Can you help me fix it?

Thanks for that.

**Comment by LiZifan** [comment]
@vanloc0301 Hi,
Can you please tell me which version of python are you running on?

**Comment by vanloc0301** [comment]
Hi, I'm is contact with you in email: vanloc0301@gmail.com.
My problem is solve.

Thank you very much.
